---
# ansible-galaxy install -r requirements.yml
roles:
  - name: encrypt
    src: git@github.com:Geexmo/encrypt.git
    scm: git
  - name: cpu
    src: git@github.com:Geexmo/cpu.git
    scm: git
  - name: net
    src: git@github.com:Geexmo/net.git
    scm: git
